### ISSUE TITLE
error launch.sh

### ISSUE THREAD

**Issue by ghost** [ecorventures/docker-gcloud#1]
/app/launch.sh: line 2: /google-cloud-sdk/bin/gcloud: No such file or directory
/app/launch.sh: line 3: /google-cloud-sdk/bin/gcloud: No such file or directory

how to resolver?

**Comment by coreybutler** [comment]
Not sure - that's a gcloud issue. I don't maintain this anymore (not using gcloud anymore).

**Comment by ghost** [comment]
ok, i solved the bug, sorry.
